# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1262290994);
user_pref("app.update.lastUpdateTime.background-update-timer", 1262290993);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1262290993);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1262290993);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1262291019);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1262290995);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://127.0.0.1/MAMP/shi.php");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1");
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5");
user_pref("extensions.lastAppVersion", "3.5");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1264883004);
